In [1]:
# import libraries
import numpy as np
import matplotlib.pyplot as plt
from sklearn import svm, datasets
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.utils import shuffle
from sklearn.metrics import classification_report,accuracy_score
import pandas as pd
from sklearn.datasets import load_iris


In [2]:
import landmarksEmot as l2
import numpy as np
from sklearn.metrics import classification_report,accuracy_score
from sklearn import svm

In [3]:
def get_data():

    X, y = l2.extract_features_labels()
    Y = np.array([y, -(y - 1)]).T
    tr_X = X[:300]
    tr_Y = Y[:300]
    te_X = X[350:550]
    te_Y = Y[350:550]
    #print(y.shape)

    return tr_X, tr_Y, te_X, te_Y, y, Y



In [9]:
get_data()

(array([[[ 58, 113],
         [ 57, 123],
         [ 57, 133],
         ...,
         [ 88, 164],
         [ 83, 163],
         [ 79, 162]],
 
        [[ 55, 111],
         [ 53, 121],
         [ 54, 132],
         ...,
         [ 89, 162],
         [ 83, 162],
         [ 79, 161]],
 
        [[ 44, 102],
         [ 45, 115],
         [ 47, 127],
         ...,
         [ 94, 160],
         [ 89, 161],
         [ 84, 161]],
 
        ...,
 
        [[ 52, 120],
         [ 53, 130],
         [ 55, 141],
         ...,
         [ 94, 157],
         [ 90, 158],
         [ 87, 158]],
 
        [[ 53, 111],
         [ 53, 121],
         [ 54, 132],
         ...,
         [ 90, 156],
         [ 85, 157],
         [ 81, 156]],
 
        [[ 52, 116],
         [ 51, 125],
         [ 51, 135],
         ...,
         [ 88, 163],
         [ 82, 162],
         [ 76, 160]]], dtype=int64),
 array([[ 1., -0.],
        [ 1., -0.],
        [ 1., -0.],
        [ 0.,  1.],
        [ 1., -0.],
        [ 1., 

In [19]:
tr_X, tr_Y, te_X, te_Y, y, Y = get_data()
print(te_X.shape)
print(te_X.reshape((te_X.size//136, 68*2)))


(4795,)
(200, 68, 2)
[[ 50 106  50 ... 156  84 156]
 [ 32 112  32 ... 155  90 155]
 [ 11 116  12 ... 157  96 157]
 ...
 [ 41 113  42 ... 158  87 158]
 [ 55 116  54 ... 156  81 155]
 [ 59 116  58 ... 153  79 152]]


In [4]:
# sklearn functions implementation
def img_SVM(training_images, training_labels, test_images, test_labels):
    classifier = svm.SVC(kernel = 'poly')
    classifier.fit(training_images, training_labels)
    pred = classifier.predict(training_images)
    print("Accuracy:", accuracy_score(training_labels, pred))

   # print(pred)
    return pred

tr_X, tr_Y, te_X, te_Y, y, Y = get_data()
pred=img_SVM(tr_X.reshape((tr_X.size//136, 68*2)), list(zip(*tr_Y))[0], te_X.reshape((te_X.size//136, 68*2)), list(zip(*te_Y))[0])

    


Accuracy: 0.93
